### ISSUE TITLE
Module Error for aerostructural case 

### ISSUE THREAD

**Issue by AbhijithMoni** [OpenMDAO/mphys#110]
Hi, 

While running the aero structural case found in `\examples\aerostructural\mach_tutorial_wing\adflow_meld_tacs` the following error appears: 

```
Traceback (most recent call last):
  File "mphys_as_2scenario.py", line 11, in <module>
    from funtofem.mphys import MeldBuilder
ModuleNotFoundError: No module named 'funtofem.mphys'
Traceback (most recent call last):
  File "mphys_as_2scenario.py", line 11, in <module>
    from funtofem.mphys import MeldBuilder
ModuleNotFoundError: No module named 'funtofem.mphys'
Traceback (most recent call last):
  File "mphys_as_2scenario.py", line 11, in <module>
    from funtofem.mphys import MeldBuilder
ModuleNotFoundError: No module named 'funtofem.mphys'
Traceback (most recent call last):
  File "mphys_as_2scenario.py", line 11, in <module>
    from funtofem.mphys import MeldBuilder
ModuleNotFoundError: No module named 'funtofem.mphys'
```
Modules funtofem and mphys are installed in the system. 

Please help me with fix this error. Thanks

**Comment by kejacobson** [comment]
Hi @AbhijithMoni, likely you need to add the root directory of funtofem to your PYTHONPATH environment variable to find your funtofem Python module. You may also need to add the funtofem `lib` directory to your LD_LIBRARY_PATH if you haven't do so already.

**Comment by AbhijithMoni** [comment]
@kejacobson, thanks for your quick reply. I do have those in my .bashrc file. 
```
export PYTHONPATH=$PYTHONPATH:"/home/mdolabuser/packages/funtofem"
export PYTHONPATH=$PYTHONPATH:"/home/mdolabuser/packages/funtofem/pyfuntofem"
export LD_LIBRARY_PATH="/home/mdolabuser/packages/funtofem/lib"

```
If I had made a mistake here please correct me. Thanks a lot

**Comment by kejacobson** [comment]
Are you able to do `import funtofem` without the `.mphys`?

When did you clone or last pull funtofem? The mphys subdirectory was added to funtofem ~2 months ago.

**Comment by AbhijithMoni** [comment]
Yes with python and `import funtofem' the module is imported without any errors.

**Comment by AbhijithMoni** [comment]
Hi @kejacobson, I was making a mistake while installing `funtofem` as you rightly pointed out. I followed the instructions available in the following link: https://dafoam.github.io/mydoc_installation_source.html#dafoam and now the import works seamlessly. 

Thank you so much for your time and input. 

Best 
Abhijith
