### ISSUE TITLE
Tacs and meld derivative tests failing

### ISSUE THREAD

**Issue by arnalj** [OpenMDAO/mphys#150]
It seems that a number of mphys tests fail "out of the box". Using MDOLab's [u22-gcc-ompi-stable docker container](https://hub.docker.com/layers/mdolab/public/u22-gcc-ompi-stable/images/sha256-ca95d1de7f9af7edbe191aa9923afd9cb8b0b1bd421e8ffa8f17537f9a0c2c55?context=explore), and running `testflo .` in `mphys/tests` gives the following:

```
The following tests failed:
test_dafoam_aero.py:
test_dafoam_aerostruct.py:
test_dafoam_derivs.py:
test_meld_derivs.py:TestXferClasses.test_derivatives
test_tacs_derivs.py:TestTACS.test_derivatives
test_tacs_partials.py:TestTACS.test_derivatives
```

I think the first three tests fail because the docker container does not include dafoam (please correct me if I'm wrong). However, should I be concerned with the last three tests? Or can I presume that mphys is installed correctly? Attached is the testflo_report.

[testflo_report.txt](https://github.com/OpenMDAO/mphys/files/11510743/testflo_report.txt)

**Comment by timryanb** [comment]
I believe the TACS/MELD tests will only run with complex compiled versions of the code (presumably your docker has only the real versions). Can't speak to the rest of the tests

**Comment by timryanb** [comment]
Closing due to PR #153 catching this issue in future
