### ISSUE TITLE
Assigning multiple design surfaces for aerodynamic optimization

### ISSUE THREAD

**Issue by AbhijithMoni** [OpenMDAO/mphys#170]
Hi,

I would like to assign multiple design surfaces to the **designSurfaceFamily** option in adflow.
```
 aero_options = {

    "designSurfaceFamily":"wingu",
}
```

In the options, there is only a possibility to assign either a string or None to the `designSurfaceFamily`  [source](https://mdolab-adflow.readthedocs-hosted.com/en/latest/options.html#designSurfaceFamily).  When I try to assign multiple surfaces I get an error which is expected based on the documentation (accepts only `str`). 
```
baseclasses.utils.error.Error:
 | Error: Datatype for option designSurfaceFamily is not valid. Expected data   |
| type (<class 'str'>, <class 'NoneType'>). Received data type is <class       |
| 'list'>
```

In my CGNS mesh, the wing geometry that I would like to optimize contains multiple components which consist of surfaces namely: `"wingu", "wingLE", "wingTE", "wingb"`. And `fuselage` and `tail` which are not a part of optimisation. 

I would like to know if there is a workaround to solve this problem of assigning multiple design surfaces to the solver at once. 

Attempting to consolidate all wing surfaces into a "wing" family using `cgns_utils` proved challenging due to the inherent complexity of handling multiblock meshes.

Coraser version of the mesh is attached. 

[uCRM_coarse.zip](https://github.com/OpenMDAO/mphys/files/14142935/uCRM_coarse.zip)

Any help is appreciated. 

Thanks

**Comment by Asthelen** [comment]
Hello, this sounds like an issue with ADflow and not MPhys. Perhaps you can try posting the issue/question there (https://github.com/mdolab/adflow) instead?

**Comment by AbhijithMoni** [comment]
It's been a couple of months since I posted my question on the ADflow platform, unfortunately, I haven't received any comments or answers. Hoping for more visibility, I brought my query here, assuming that since ADflow is an integral component of MPhys, it might get attention.

https://github.com/mdolab/adflow/discussions/334#discussion-5954181

Thank you for your response. I'll take your suggestion and re-post my query in the ADflow forum.
