### ISSUE TITLE
Use Continious Integration (CI) tool to automatically run tests on PRs and commits.

### ISSUE THREAD

**Issue by joanibal** [OpenMDAO/mphys#34]
To ensure functionality of the code doesn't silently break, we should be using CI. This is especially import for projects with many collaborators as it is unlikely that one person will understand how their change will affect each of the features added by others. 

I suggest Travis CI because it has been used successfully by the MDOLab and the OpenMDAO dev-team.

**Comment by kejacobson** [comment]
Enabled in #70 using github actions.
