### ISSUE TITLE
extend the usage of shape_by_conn

### ISSUE THREAD

**Issue by anilyil** [OpenMDAO/mphys#55]
After PR #51 is merged, most of the code will be using shape by connection to size the inputs to components. The convention originally followed was to explicitly size all outputs and have as many inputs as possible be shaped by connection. However, there is a possibility to utilize the feature even more by relaxing this convention. We should look into possible simplification of the code by using the copy_shape feature, while still using the "downstream" mode of shape information transfer. For examples, see: https://github.com/OpenMDAO/mphys/pull/51#discussion_r591712650 and https://github.com/OpenMDAO/mphys/pull/51#discussion_r595499796 and https://github.com/OpenMDAO/mphys/pull/51#discussion_r591705069

**Comment by kejacobson** [comment]
#53 changed to standard of using shape_by_conn for all vector inputs
